name = "SchwingerMPS"
uuid = "7ffa9dc2-283a-482e-bb61-4d0bcbbe1efd"
authors = ["JaydevSR <jaydevsrao@gmail.com>"]
version = "0.1.0"

[deps]
ITensorMPS = "0d1a4710-d33b-49a5-8f18-73bdf49b47e2"
ITensors = "9136182c-28ba-11e9-034c-db9fb085ebd5"

[compat]
ITensorMPS = "0.3.8"
ITensors = "0.8.0"
